models/Category.php
<?php

namespace app\models;

use app\components\myRedirect;
use app\components\storageImage\eventOfImage;
use kartik\tree\models\Tree;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property int $root
 * @property int $lft
 * @property int $rgt
 * @property int $lvl
 * @property string $type
 * @property string $name
 * @property string $icon
 * @property int $icon_type
 * @property int $active
 * @property int $selected
 * @property int $disabled
 * @property int $readonly
 * @property int $visible
 * @property int $collapsed
 * @property int $movable_u
 * @property int $movable_d
 * @property int $movable_l
 * @property int $movable_r
 * @property int $removable
 * @property int $removable_all
 */
class Category extends Tree
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    public function beforeSave($insert)// перед записью
    {
        if (parent::beforeSave($insert))
        {
            eventOfImage::beforeSave($insert, $this); // сохранение и редактирование изображений.

            return true;
        }

        else
            return false;
    }

    public function afterDelete()
    {
        parent::afterDelete();

        eventOfImage::afterDelete($this); // удаление изображений.
    }

    /**
     * Делаем запись в таблицу "redirect", где хранятся новые и старые адреса, для переадресации.
     *
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        myRedirect::urlMain($this);
        myRedirect::urlChildren();
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $rules = parent::rules();
        $rules[] = [['type', 'url', 'name'], 'required'];
        $rules[] = [['name', 'url'], 'string', 'max' => 60];
        $rules[] = [['type', 'image', 'title', 'description', 'tags'], 'string', 'max' => 255];

        return $rules;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        $attr = parent::attributeLabels();
        $attr['type'] = 'Тип';
        $attr['url'] = 'Адрес';
        $attr['description'] = 'Краткое описание';
        $attr['tags'] = 'Теги';
        $attr['image'] = 'Изображение (Пропорции 356 х 246)';
        return $attr;
    }


    public function getContent()
    {
        return $this->hasOne(Content::class, ['category_id' => 'id']);
    }
}

controllers/CategoryController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\search\ContentSearch;
use Yii;
use app\models\search\CategorySearch;
use yii\web\Controller;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    public $layout = 'admin';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'as AccessBehavior' => [
                'class' => \developeruz\db_rbac\behaviors\AccessBehavior::className(),
                'rules' =>
                    ['category' =>
                        [
                            [
                                'allow' => true,
                                'roles' => ['admin'],
                            ],
                        ]
                    ]
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        // получаем данные категорий
        $treeViewModel = new CategorySearch();
        $treeView = $treeViewModel->treeView();

        // получаем данные контента
        $searchModel = new ContentSearch();
        $dataProvider = $searchModel->modify(Yii::$app->request->queryParams);

        return $this->render('index', [
            'treeView' => $treeView,
            'treeCheck' => Category::find()->one(),

            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
}

controllers/ContentController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Faq;
use app\models\Order;
use app\models\Redirect;
use app\models\search\ContentSearch;
use Yii;
use app\models\Content;
use app\widgets\extended\pagination\Pagination;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ContentController implements the CRUD actions for Content model.
 */
class ContentController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'as AccessBehavior' => [
                'class' => \developeruz\db_rbac\behaviors\AccessBehavior::className(),
                'rules' =>
                    ['content' =>
                        [
                            [
                                'actions' => ['main', 'many', 'one'],
                                'allow' => true,
                            ],
                            [
                                'allow' => true,
                                'roles' => ['admin'],
                            ],
                        ]
                    ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Отображения категории hasMany
     * Lists all Content models.
     * @return mixed
     */
    public function actionMany(Category $current, $redirect = null)
    {

        if(!empty($redirect))
        {
            return $this->redirect($redirect, 301);
        }

        $order = new Order();
        $faq = new Faq();
        $model = new Content;

        $searchModel = new ContentSearch();
        $dataProvider = $searchModel->search($current);

        // Подключаем свою пагинацию для динамических адресов
        $pages = new Pagination([
            'defaultPageSize' => $dataProvider->pagination->defaultPageSize,
            'totalCount' => $dataProvider->query->count(),
            'route' => Yii::$app->request->pathInfo,
        ]);

        if(!empty(Yii::$app->session['model']))
        {
            $model->load(Yii::$app->session['model']);
            unset(Yii::$app->session['model']);
        }


        return $this->render($current->type.'/'.$current->type.'Many', [
            'dataProvider' => $dataProvider,
            'meta' => $current,
            'model' => $model,
            'order' => $order,
            'faq' => $faq,
            'pages' => $pages,
        ]);

    }

    /**
     * Отображение конкретной записи.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionOne(Content $current, $redirect = null)
    {
        if(!empty($redirect))
        {
            return $this->redirect($redirect.'/'.$current->url, 301);
        }

        if(!empty(Yii::$app->session['model']))
        {
            $current->load(Yii::$app->session['model']);
            unset(Yii::$app->session['model']);
        }

        return $this->render($current->type.'/'.$current->type.'One', [
            'model' => $current,
            'meta' => $current->category,
        ]);
    }

    /**
     * Creates a new Content model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout='admin';

        $model = new Content();

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            unset(Yii::$app->session['model']);

            if (Yii::$app->request->get('redirect') != '/content/create')
                return $this->redirect([Yii::$app->request->get('redirect')]);

            else
                return $this->redirect('../category');
        }

        elseif ($model->load(Yii::$app->request->post()) && !$model->save())
        {

            Yii::$app->session['model'] = Yii::$app->request->post();

            //echo '<pre>'; print_r(Yii::$app->session['model']); echo '</pre>';
            
            Yii::$app->session->setFlash('notUnique');
            return $this->redirect([Yii::$app->request->get('redirect')]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Content model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $this->layout='admin';

        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            // Если редактируется не из админки
            if (Yii::$app->request->get('redirect') != 'content') {

                if (Yii::$app->request->get('update') == 'many')
                    return $this->redirect(Yii::$app->request->get('redirect'));

                else
                    return $this->redirect(Yii::$app->request->get('redirect') . '/' . $model->url);
            }

            // Если редактируется в админке
            else
                return $this->redirect('../category');
        }

        elseif ($model->load(Yii::$app->request->post()) && !$model->save())
        {

            Yii::$app->session['model'] = Yii::$app->request->post();

            //echo '<pre>'; print_r(Yii::$app->session['model']); echo '</pre>';

            Yii::$app->session->setFlash('notUnique');
            return $this->redirect([Yii::$app->request->get('redirect')]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Content model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        if (!empty(Yii::$app->request->get('redirect')))
            return $this->redirect([Yii::$app->request->get('redirect')]);

        else
            return $this->redirect('../category');
    }

    // Для виджета position
    public function actionMoveUp($id)
    {
        $this->findModel($id)->moveNext();

        if (!empty(Yii::$app->request->get('redirect')))
            return $this->redirect([Yii::$app->request->get('redirect')]);

        else
            return $this->redirect('../category');
    }

    // Для виджета position
    public function actionMoveDown($id)
    {
        $this->findModel($id)->movePrev();

        if (!empty(Yii::$app->request->get('redirect')))
            return $this->redirect([Yii::$app->request->get('redirect')]);

        else
            return $this->redirect('../category');
    }

    protected function findModel($id)
    {
        if (($model = Content::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/category/index.php
<?php

use kartik\tree\TreeView;
use kartik\tree\Module;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\ContentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Меню и содержимое';
$this->params['breadcrumbs'][] = $this->title;


?>

<? $this->registerJsFile("myCssJs/js/bootstrap/bootstrap.js",['depends' => [\yii\web\JqueryAsset::className()]]) ?>

<!-- page title -->
<header id="page-header" style="margin-bottom: 30px">
    <h1><?= $this->title ?></h1>
    <ol class="breadcrumb">
        <li><a href="#">Наполнение сайта</a></li>
        <li class="active"><?= $this->title ?></li>
    </ol>
</header>
<!-- /page title -->

<div class="panel panel-default">
    <div class="panel-heading">
        <span class="title elipsis">
            <strong style="font-size: 20px">Категории</strong>
        </span>
    </div>
    <div class="panel-body">

        <?
        $s = null;
        /** @var array $treeView */
        /** @var array $treeCheck */
        echo TreeView::widget([
            'query' => $treeView, // передаем данные из таблицы category

            'options' => ['id' => 'myTree'],

            'topRootAsHeading' => true, // this will override the headingOptions
            'detailOptions' => ['style' => 'background-color:#f6f8f8;'],
            'treeOptions' => ['style' => 'height:395px;'],
            'mainTemplate' =>
                '<div class="row darkColor">
                                <div class="col-sm-5">
                                    {wrapper}
                                </div>
                                <div class="col-sm-7">
                                    {detail}
                                </div>
                            </div>',

            'headerTemplate' =>
                '<div class="row">
                                <div class="col-sm-12">
                                    {search}
                                </div>
                            </div>',


            // single query fetch to render the tree
            // use the Product model you have in the previous step
            'headingOptions' => ['label' => false],
            'fontAwesome' => true,     // optional
            'allowNewRoots' => !empty($treeCheck) ? false : true, // выводить кнопку создания дерева
            'isAdmin' => !empty($treeCheck) ? false : true,         // optional (toggle to enable admin mode)
            'iconEditSettings'=> ['show' => 'none'],
            'displayValue' => $treeCheck->root,        // initial display value
            'softDelete' => false,       // defaults to true
            'cacheSettings' => [
                'enableCache' => false   // defaults to true
            ],

            'showIDAttribute' => false,
            'showNameAttribute' => false,

            'nodeAddlViews' => [
                Module::VIEW_PART_2 => '@app/views/category/context/_form_2',
            ]
        ]);

        ?>

    </div>
</div>



<div class="panel panel-default">

    <?php Pjax::begin(); ?>

    <!-- Pjax портит отображение, поэтому прописываем стиль -->
    <div class="panel-heading" style="background-color: white; text-transform: uppercase; border-color: #ddd;">
        <span class="title elipsis">
            <strong style="font-size: 20px">Содержимое</strong>
        </span>
        <ul class="options pull-right list-inline">

            <li><?= Html::a('<i class="fa fa-paper-plane"></i>Добавить запись',
                    ['content/create'],
                    ['class' => 'btn btn-3d btn-sm btn-green',
                        'title' => 'Создание новой записи',
                    ])
                ?></li>

            <li><?= Html::a('<i class="fa fa-filter"></i>Фильтр по категории',
                    ['/category?active=3'],
                    ['class' => 'btn btn-3d btn-sm btn-blue',
                        'onmouseenter' => 'category_filter()',
                        'title' => 'Выберите необходимую категорию выше',
                        'id' => 'button_filter',
                    ])
                ?></li>
            <li><?= Html::a('<i class="fa fa-refresh"></i>Сбросить',
                    ['/category?active=3'],
                    ['class' => 'btn btn-3d btn-sm btn-purple',
                        'title' => 'Отобразить все записи',
                    ])
                ?></li>
        </ul>
    </div>


    <div class="panel-body">
        <?
        echo GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout'=>"\n{items}\n{pager}",

            'tableOptions' => [
                'class' => 'table table-striped table-hover table-bordered dataTable no-footer',
            ],

            'columns' => [

                ['attribute' => 'name',
                    'filterInputOptions' => ['class' => 'form-control', 'placeholder' => 'Поиск по заголовку...'],
                ],

                ['attribute' => 'category_id',
                    'value' => 'category.name',

                    'headerOptions' => [
                        'style' => 'text-align: center',
                        'width' => '360',
                        'hidden'
                    ],

                    'filterInputOptions' => ['type' => 'hidden'],

                    'contentOptions' => [
                        'style' => 'text-align: center',
                    ]
                ],

                ['attribute' => 'type',
                    'value' => 'oneType.name',

                    'header' => 'Дизайн',
                    'headerOptions' => ['width' => '60'],
                    'contentOptions' => ['style' => 'text-align: center'],
                ],

                ['class' => 'yii\grid\ActionColumn',
                    'header' => 'Действия',
                    'headerOptions' => ['style' => 'text-align: center', 'width' => '105'] ,
                    'contentOptions' => ['style' => 'text-align: center;'],
                    'urlCreator'=>function($action, $model, $key, $index){
                        return ['content/'. $action, 'id' => $model->id];

                    },
                    'template' => '{moveUp} {moveDown} {update} {delete} ',
                    'buttons' => [
                        'moveUp' => function($url, $model, $key) {     // render your custom button
                            return Html::a("<i class='glyphicon glyphicon-triangle-top'></i>", ["content/move-up", "id" => $model->id], ['data-method' => 'post']);
                        },
                        'moveDown' => function($url, $model, $key) {     // render your custom button
                            return Html::a("<i class='glyphicon glyphicon-triangle-bottom'></i>", ["content/move-down", "id" => $model->id], ['data-method' => 'post']);
                        },
                    ]
                ],

            ],
        ]);
        ?>
    </div>

    <?php Pjax::end(); ?>

</div>