models/Content.php
<?php

namespace app\models;

use app\components\storageImage\eventOfImage;
use app\modules\position\PositionBehavior;
use dektrium\user\models\User;
use yii\db\ActiveRecord;
use yii2mod\comments\models\CommentModel;

/**
 * This is the model class for table "content".
 *
 * @property int $id
 * @property int $category_id
 * @property int $author_id
 * @property string $name
 * @property string $image
 * @property string $text
 * @property string $description
 * @property string $keywords
 * @property int $hits
 * @property string $data
 * @property int $position
 */
class Content extends ActiveRecord
{

    public function behaviors()
    {
        return [
            'positionBehavior' => [
                'class' => PositionBehavior::class,
                'groupAttributes' => [
                    'category_id' // multiple lists varying by 'categoryId'
                ],
            ],
        ];
    }

    public function beforeSave($insert)// перед записью
    {
        if (parent::beforeSave($insert))
        {
            eventOfImage::beforeSave($insert, $this); // сохранение и редактирование изображений.

            return true;
        }

        else
            return false;

    }

    public function afterDelete()// после удалением quote
    {
        parent::afterDelete();

        eventOfImage::afterDelete($this); // удаление изображений.
    }


    public static function tableName()
    {
        return 'content';
    }

    /**
     * @inheritdoc
     */

    public function rules()
    {
        return [
            [['category_id', 'author_id', 'hits', 'position', 'price', 'price_old'], 'integer'],
            [['image', 'text'], 'string'],
            [['date'], 'safe'],
            [['url'], 'string', 'max' => 60],
            [['type', 'name', 'title', 'description', 'keywords', 'section', 'source'], 'string', 'max' => 200],
            [['category_id', 'type', 'name', 'url'], 'required'],

            [['url'], 'uniqueInCategory'],
        ];
    }

    // Проверка на уникальность в текущей категории. В других категориях совпадения не критичны.
    public function uniqueInCategory ($attribute) {

        $leaves = Content::find()->where(['category_id' => $this->category_id])->all();

        foreach ($leaves as $value)
        {
            //Если найдены совпадения в текущей категории и адрес записи изменился.
            if ($this->url == $value->url && $this->oldAttributes['url'] != $this->url)
            {
                $this->addError($attribute, 'Запись с указанным адресом в данной категории уже существует.
                            Измените адрес.');
            }
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Категория',
            'author_id' => 'Автор',
            'title' => 'Наименование для поисковика',
            'type' => 'Дизайн страницы',
            'url' => 'Адрес',
            'name' => 'Заголовок',
            'image' => 'Изображение',
            'text' => 'Текст',
            'price' => 'Цена',
            'price_old' => 'Старая цена',
            'description' => 'Краткое описание',
            'keywords' => 'Ключевые слова',
            'section' => 'Раздел',
            'source' => 'Источник',
            'hits' => 'Просмотры',
            'date' => 'Дата',
            'position' => 'Позиция',
        ];
    }

    public function getCategory()
    {
        return $this->hasOne(Category::class, ['id' => 'category_id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'author_id']);
    }

    public function getOneType()
    {
        return $this->hasOne(Type::class, ['type' => 'type']);
    }

    public function getComment()
    {
        return $this->hasMany(CommentModel::class, ['entityId' => 'id'])->select(['entityId', 'status']); // использую для счетчика комментариев
    }
}

controllers/ContentController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Faq;
use app\models\Order;
use app\models\Redirect;
use app\models\search\ContentSearch;
use Yii;
use app\models\Content;
use app\widgets\extended\pagination\Pagination;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ContentController implements the CRUD actions for Content model.
 */
class ContentController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'as AccessBehavior' => [
                'class' => \developeruz\db_rbac\behaviors\AccessBehavior::className(),
                'rules' =>
                    ['content' =>
                        [
                            [
                                'actions' => ['main', 'many', 'one'],
                                'allow' => true,
                            ],
                            [
                                'allow' => true,
                                'roles' => ['admin'],
                            ],
                        ]
                    ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Отображения категории hasMany
     * Lists all Content models.
     * @return mixed
     */
    public function actionMany(Category $current, $redirect = null)
    {

        if(!empty($redirect))
        {
            return $this->redirect($redirect, 301);
        }

        $order = new Order();
        $faq = new Faq();
        $model = new Content;

        $searchModel = new ContentSearch();
        $dataProvider = $searchModel->search($current);

        // Подключаем свою пагинацию для динамических адресов
        $pages = new Pagination([
            'defaultPageSize' => $dataProvider->pagination->defaultPageSize,
            'totalCount' => $dataProvider->query->count(),
            'route' => Yii::$app->request->pathInfo,
        ]);

        if(!empty(Yii::$app->session['model']))
        {
            $model->load(Yii::$app->session['model']);
            unset(Yii::$app->session['model']);
        }


        return $this->render($current->type.'/'.$current->type.'Many', [
            'dataProvider' => $dataProvider,
            'meta' => $current,
            'model' => $model,
            'order' => $order,
            'faq' => $faq,
            'pages' => $pages,
        ]);

    }

    /**
     * Отображение конкретной записи.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionOne(Content $current, $redirect = null)
    {
        if(!empty($redirect))
        {
            return $this->redirect($redirect.'/'.$current->url, 301);
        }

        if(!empty(Yii::$app->session['model']))
        {
            $current->load(Yii::$app->session['model']);
            unset(Yii::$app->session['model']);
        }

        return $this->render($current->type.'/'.$current->type.'One', [
            'model' => $current,
            'meta' => $current->category,
        ]);
    }

    /**
     * Creates a new Content model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout='admin';

        $model = new Content();

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            unset(Yii::$app->session['model']);

            if (Yii::$app->request->get('redirect') != '/content/create')
                return $this->redirect([Yii::$app->request->get('redirect')]);

            else
                return $this->redirect('../category');
        }

        elseif ($model->load(Yii::$app->request->post()) && !$model->save())
        {

            Yii::$app->session['model'] = Yii::$app->request->post();

            //echo '<pre>'; print_r(Yii::$app->session['model']); echo '</pre>';
            
            Yii::$app->session->setFlash('notUnique');
            return $this->redirect([Yii::$app->request->get('redirect')]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Content model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $this->layout='admin';

        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            // Если редактируется не из админки
            if (Yii::$app->request->get('redirect') != 'content') {

                if (Yii::$app->request->get('update') == 'many')
                    return $this->redirect(Yii::$app->request->get('redirect'));

                else
                    return $this->redirect(Yii::$app->request->get('redirect') . '/' . $model->url);
            }

            // Если редактируется в админке
            else
                return $this->redirect('../category');
        }

        elseif ($model->load(Yii::$app->request->post()) && !$model->save())
        {

            Yii::$app->session['model'] = Yii::$app->request->post();

            //echo '<pre>'; print_r(Yii::$app->session['model']); echo '</pre>';

            Yii::$app->session->setFlash('notUnique');
            return $this->redirect([Yii::$app->request->get('redirect')]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Content model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        if (!empty(Yii::$app->request->get('redirect')))
            return $this->redirect([Yii::$app->request->get('redirect')]);

        else
            return $this->redirect('../category');
    }

    // Для виджета position
    public function actionMoveUp($id)
    {
        $this->findModel($id)->moveNext();

        if (!empty(Yii::$app->request->get('redirect')))
            return $this->redirect([Yii::$app->request->get('redirect')]);

        else
            return $this->redirect('../category');
    }

    // Для виджета position
    public function actionMoveDown($id)
    {
        $this->findModel($id)->movePrev();

        if (!empty(Yii::$app->request->get('redirect')))
            return $this->redirect([Yii::$app->request->get('redirect')]);

        else
            return $this->redirect('../category');
    }

    protected function findModel($id)
    {
        if (($model = Content::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/content/blog/_blog.php
<?php

use app\classes\WidHelper;
use app\widgets\modalBody;
use yii\bootstrap\Html;

?>

<? modalBody::update($model, $model->category) ?>

<!-- blogpost start -->
                <article class="blogpost">
                    <div class="row grid-space-10">
                        <div class="col-lg-6">
                            <div class="overlay-container">
                                <?= WidHelper::image($model) ?>
                                <?= Html::a('<i class="fa fa-link"></i>', ['content/one', 'model' => $model], ['class' => 'overlay-link']) ?>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <header>
                                <h2>
                                    <?= Html::a($model->name, ['content/one', 'model' => $model]) ?>
                                    <? WidHelper::updateDelete($model) ?>
                                </h2>
                                <div class="post-info">
                        <span class="post-date">
                          <i class="icon-calendar"></i>
                            <?= Yii::$app->formatter->asDate($model->date) ?>
                        </span>
                                    <span class="submitted"><i class="icon-user-1"></i><a href="#"><?= $model->user->username ?></a></span>
                                    <span class="comments"><i class="icon-chat"></i> <a href="#"><? WidHelper::commentCount($model) ?></a></span>
                                </div>
                            </header>
                            <div class="blogpost-content">

                                <? WidHelper::text($model, 30) ?>
                            </div>
                        </div>
                    </div>
                    <footer class="clearfix">
                        <div class="tags pull-left"></div>
                    </footer>
                </article>
                <!-- blogpost end -->

views/content/blog/blogMany.php
<?php

use app\classes\WidHelper;
use app\widgets\modalBody;
use yii\widgets\ListView;

/**
 * @var $this yii\web\View
 * @var $meta
 * @var $pages
 */
$this->title = $meta->name;
Yii::$app->view->params['modelMany'] = $model;
Yii::$app->view->params['meta'] = $meta;
?>

<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-lg-8">
                <div style="margin-bottom: 30px">
                    <? modalBody::pencil('head', $meta) ?>
                </div>

                <!-- page-title start -->
                <!-- ================ -->
                <h1 class="page-title"><?= $meta->name ?></h1>

                <? WidHelper::alertError('notUnique', 'Запись с указанным адресом в данной категории уже существует') ?>
                <hr />
                <!-- page-title end -->

                <?php
                // echo '<div class="read" style="text-align: right"><b>Сортировать по:</b> &nbsp&nbsp' . $sort->link('name') . ' &nbsp;&nbsp;&nbsp;&nbsp;' . $sort->link('id') . '</div></br>';

                echo ListView::widget([
                    'dataProvider' => $dataProvider,

                    'layout' => "{items}",

                    'itemOptions' => [
                        'tag' => false,
                    ],
                    'options' => [
                        'tag' => 'article',
                        'class' => 'post',
                        // 'id' => 'list-wrapper',
                    ],
                    'itemView' => '_blog',

                    'viewParams' => [
                        'meta' => $meta,
                    ],
                ]);

                ?>

                <?= \yii\widgets\LinkPager::widget([
                    'pagination' => $pages,
                ]);
                ?>



            </div>
            <!-- main end -->

            <!-- sidebar start -->
            <!-- ================ -->
            <aside class="col-lg-4 col-xl-3 ml-xl-auto">
                <div class="sidebar">
                    <div class="block clearfix">
                        <h3 class="title">Sidebar menu</h3>
                        <div class="separator-2"></div>
                        <nav>
                            <ul class="nav flex-column">
                                <li class="nav-item"><a class="nav-link" href="index.html">Home</a></li>
                                <li class="nav-item"><a class="nav-link active" href="blog-large-image-right-sidebar.html">Blog</a></li>
                                <li class="nav-item"><a class="nav-link" href="portfolio-grid-2-3-col.html">Portfolio</a></li>
                                <li class="nav-item"><a class="nav-link" href="page-about.html">About</a></li>
                                <li class="nav-item"><a class="nav-link" href="page-contact.html">Contact</a></li>
                            </ul>
                        </nav>
                    </div>

                    <div class="block clearfix">
                        <h3 class="title">Latest tweets</h3>
                        <div class="separator-2"></div>
                        <ul class="tweets">
                            <li>
                                <i class="fa fa-twitter"></i>
                                <p><a href="#">@lorem</a> ipsum dolor sit amet, consectetur adipisicing elit. Mollitia, aliquid, et molestias nesciunt <a href="#">http://t.co/dzLEYGeEH9</a>.</p><span>16 hours ago</span>
                            </li>
                            <li>
                                <i class="fa fa-twitter"></i>
                                <p><a href="#">@lorem</a> ipsum dolor sit amet, consectetur adipisicing elit. Mollitia, aliquid, et molestias nesciunt <a href="#">http://t.co/dzLEYGeEH9</a>.</p><span>16 hours ago</span>
                            </li>
                        </ul>
                    </div>
                    <div class="block clearfix">
                        <h3 class="title">Popular Tags</h3>
                        <div class="separator-2"></div>
                        <div class="tags-cloud">
                            <div class="tag">
                                <a href="#">energy</a>
                            </div>
                            <div class="tag">
                                <a href="#">business</a>
                            </div>
                            <div class="tag">
                                <a href="#">food</a>
                            </div>
                            <div class="tag">
                                <a href="#">fashion</a>
                            </div>
                            <div class="tag">
                                <a href="#">finance</a>
                            </div>
                            <div class="tag">
                                <a href="#">culture</a>
                            </div>
                            <div class="tag">
                                <a href="#">health</a>
                            </div>
                            <div class="tag">
                                <a href="#">sports</a>
                            </div>
                            <div class="tag">
                                <a href="#">life style</a>
                            </div>
                            <div class="tag">
                                <a href="#">books</a>
                            </div>
                            <div class="tag">
                                <a href="#">lorem</a>
                            </div>
                            <div class="tag">
                                <a href="#">ipsum</a>
                            </div>
                            <div class="tag">
                                <a href="#">responsive</a>
                            </div>
                            <div class="tag">
                                <a href="#">style</a>
                            </div>
                            <div class="tag">
                                <a href="#">finance</a>
                            </div>
                            <div class="tag">
                                <a href="#">sports</a>
                            </div>
                            <div class="tag">
                                <a href="#">technology</a>
                            </div>
                            <div class="tag">
                                <a href="#">support</a>
                            </div>
                            <div class="tag">
                                <a href="#">life style</a>
                            </div>
                            <div class="tag">
                                <a href="#">books</a>
                            </div>
                        </div>
                    </div>
                    <div class="block clearfix">
                        <h3 class="title">Testimonial</h3>
                        <div class="separator-2"></div>
                        <blockquote class="margin-clear">
                            <p>Design is not just what it looks like and feels like. Design is how it works.</p>
                            <footer><cite title="Source Title">Steve Jobs </cite></footer>
                        </blockquote>
                        <blockquote class="margin-clear">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos dolorem.</p>
                            <footer><cite title="Source Title">Steve Doe </cite></footer>
                        </blockquote>
                    </div>
                    <div class="block clearfix">
                        <h3 class="title">Latest News</h3>
                        <div class="separator-2"></div>
                        <div class="media margin-clear">
                            <div class="d-flex pr-2">
                                <div class="overlay-container">
                                    <img class="media-object" src="images/blog-thumb-1.jpg" alt="blog-thumb">
                                    <a href="blog-post.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                                </div>
                            </div>
                            <div class="media-body">
                                <h6 class="media-heading"><a href="blog-post.html">Lorem ipsum dolor sit amet...</a></h6>
                                <p class="small margin-clear"><i class="fa fa-calendar pr-10"></i>Mar 23, 2017</p>
                            </div>
                        </div>
                        <hr>
                        <div class="media margin-clear">
                            <div class="d-flex pr-2">
                                <div class="overlay-container">
                                    <img class="media-object" src="images/blog-thumb-2.jpg" alt="blog-thumb">
                                    <a href="blog-post.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                                </div>
                            </div>
                            <div class="media-body">
                                <h6 class="media-heading"><a href="blog-post.html">Lorem ipsum dolor sit amet...</a></h6>
                                <p class="small margin-clear"><i class="fa fa-calendar pr-10"></i>Mar 22, 2017</p>
                            </div>
                        </div>
                        <hr>
                        <div class="media margin-clear">
                            <div class="d-flex pr-2">
                                <div class="overlay-container">
                                    <img class="media-object" src="images/blog-thumb-3.jpg" alt="blog-thumb">
                                    <a href="blog-post.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                                </div>
                            </div>
                            <div class="media-body">
                                <h6 class="media-heading"><a href="blog-post.html">Lorem ipsum dolor sit amet...</a></h6>
                                <p class="small margin-clear"><i class="fa fa-calendar pr-10"></i>Mar 21, 2017</p>
                            </div>
                        </div>
                        <hr>
                        <div class="media margin-clear">
                            <div class="d-flex pr-2">
                                <div class="overlay-container">
                                    <img class="media-object" src="images/blog-thumb-4.jpg" alt="blog-thumb">
                                    <a href="blog-post.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                                </div>
                            </div>
                            <div class="media-body">
                                <h6 class="media-heading"><a href="blog-post.html">Lorem ipsum dolor sit amet...</a></h6>
                                <p class="small margin-clear"><i class="fa fa-calendar pr-10"></i>Mar 21, 2017</p>
                            </div>
                        </div>
                        <div class="text-right space-top">
                            <a href="blog-large-image-right-sidebar.html" class="link-dark"><i class="fa fa-plus-circle pl-1 pr-1"></i>More</a>
                        </div>
                    </div>
                    <div class="block clearfix">
                        <h3 class="title">Text Sample</h3>
                        <div class="separator-2"></div>
                        <p class="margin-clear">Debitis eaque officia illo impedit ipsa earum <a href="#">cupiditate repellendus</a> corrupti nisi nemo, perspiciatis optio harum, hic laudantium nulla maiores rem sit magni neque nihil sequi temporibus. Laboriosam ipsum reiciendis iste, nobis obcaecati, a autem voluptatum odio? Recusandae officiis dicta quod qui eligendi.</p>
                    </div>
                    <div class="block clearfix">
                        <form role="search">
                            <div class="form-group has-feedback">
                                <input type="text" class="form-control" placeholder="Search">
                                <i class="fa fa-search form-control-feedback"></i>
                            </div>
                        </form>
                    </div>
                </div>
            </aside>
            <!-- sidebar end -->

        </div>
    </div>
</section>
<!-- main-container end -->

Отображать по:
<?//= Html::a('10', Url::current(['per-page' => '10']));?><!--,-->
<?//= Html::a('25', Url::current(['per-page' => '25']));?><!--,-->
<?//= Html::a('50', Url::current(['per-page' => '50']));?>
<?//= Html::a('100', Url::current(['per-page' => '100']));?>